
HEADERS += \
    $$SRC_LOC/cds_model/hgenre.h \
    $$SRC_LOC/cds_model/hdatetimerange.h \
    $$SRC_LOC/cds_model/hsortinfo.h \
    $$SRC_LOC/cds_model/hdeviceudn.h \
    $$SRC_LOC/cds_model/hprice.h \
    $$SRC_LOC/cds_model/hmatching_id.h \
    $$SRC_LOC/cds_model/hchannel_id.h \
    $$SRC_LOC/cds_model/hcdsclassinfo.h \
    $$SRC_LOC/cds_model/hpersonwithrole.h \
    $$SRC_LOC/cds_model/hcontentduration.h \
    $$SRC_LOC/cds_model/hchannelgroupname.h \
    $$SRC_LOC/cds_model/hforeignmetadata.h \
    $$SRC_LOC/cds_model/hprogramcode.h \
    $$SRC_LOC/cds_model/hstatevariablecollection.h \
    $$SRC_LOC/cds_model/hscheduledtime.h \
    $$SRC_LOC/cds_model/datasource/habstract_cds_datasource_p.h \
    $$SRC_LOC/cds_model/datasource/habstract_cds_datasource.h \
    $$SRC_LOC/cds_model/datasource/hcds_datasource_p.h \
    $$SRC_LOC/cds_model/datasource/hcds_datasource.h \
    $$SRC_LOC/cds_model/datasource/hrootdir.h \
    $$SRC_LOC/cds_model/datasource/hfsys_datasource.h \
    $$SRC_LOC/cds_model/datasource/hfsys_datasource_p.h \
    $$SRC_LOC/cds_model/datasource/hfsys_datasource_configuration.h \
    $$SRC_LOC/cds_model/datasource/hfsys_datasource_configuration_p.h \
    $$SRC_LOC/cds_model/datasource/hcds_datasource_configuration_p.h \
    $$SRC_LOC/cds_model/datasource/hcds_datasource_configuration.h \
    $$SRC_LOC/cds_model/model_mgmt/hcds_fsys_reader_p.h \
    $$SRC_LOC/cds_model/model_mgmt/hcdsobjectdata_p.h \
    $$SRC_LOC/cds_model/model_mgmt/hcds_dlite_serializer.h \
    $$SRC_LOC/cds_model/model_mgmt/hcdsproperty_db.h \
    $$SRC_LOC/cds_model/model_mgmt/hcdsproperty_db_p.h \
    $$SRC_LOC/cds_model/model_mgmt/hcdsproperties.h \
    $$SRC_LOC/cds_model/model_mgmt/hcdsproperty.h \
    $$SRC_LOC/cds_model/model_mgmt/hcdspropertyinfo.h \
    $$SRC_LOC/cds_model/model_mgmt/hcds_dlite_serializer_p.h \
    $$SRC_LOC/cds_model/cds_objects/hobject.h \
    $$SRC_LOC/cds_model/cds_objects/hobject_p.h \
    $$SRC_LOC/cds_model/cds_objects/hitem.h \
    $$SRC_LOC/cds_model/cds_objects/hitem_p.h \
    $$SRC_LOC/cds_model/cds_objects/haudioitem.h \
    $$SRC_LOC/cds_model/cds_objects/haudioitem_p.h \
    $$SRC_LOC/cds_model/cds_objects/haudioprogram.h \
    $$SRC_LOC/cds_model/cds_objects/haudioprogram_p.h \
    $$SRC_LOC/cds_model/cds_objects/haudiobroadcast.h \
    $$SRC_LOC/cds_model/cds_objects/haudiobroadcast_p.h \
    $$SRC_LOC/cds_model/cds_objects/hbookmarkitem.h \
    $$SRC_LOC/cds_model/cds_objects/hbookmarkitem_p.h \
    $$SRC_LOC/cds_model/cds_objects/hepgitem.h \
    $$SRC_LOC/cds_model/cds_objects/hepgitem_p.h \
    $$SRC_LOC/cds_model/cds_objects/haudiobook.h \
    $$SRC_LOC/cds_model/cds_objects/haudiobook_p.h \
    $$SRC_LOC/cds_model/cds_objects/hmusictrack.h \
    $$SRC_LOC/cds_model/cds_objects/hmusictrack_p.h \
    $$SRC_LOC/cds_model/cds_objects/hmusicvideoclip.h \
    $$SRC_LOC/cds_model/cds_objects/hmusicvideoclip_p.h \
    $$SRC_LOC/cds_model/cds_objects/himageitem.h \
    $$SRC_LOC/cds_model/cds_objects/hmovie.h \
    $$SRC_LOC/cds_model/cds_objects/hmovie_p.h \
    $$SRC_LOC/cds_model/cds_objects/himageitem_p.h \
    $$SRC_LOC/cds_model/cds_objects/hphoto.h \
    $$SRC_LOC/cds_model/cds_objects/hphoto_p.h \
    $$SRC_LOC/cds_model/cds_objects/htextitem.h \
    $$SRC_LOC/cds_model/cds_objects/htextitem_p.h \
    $$SRC_LOC/cds_model/cds_objects/hplaylistitem.h \
    $$SRC_LOC/cds_model/cds_objects/hplaylistitem_p.h \
    $$SRC_LOC/cds_model/cds_objects/hvideoitem.h \
    $$SRC_LOC/cds_model/cds_objects/hvideoitem_p.h \
    $$SRC_LOC/cds_model/cds_objects/hvideoprogram.h \
    $$SRC_LOC/cds_model/cds_objects/hvideoprogram_p.h \
    $$SRC_LOC/cds_model/cds_objects/hvideobroadcast.h \
    $$SRC_LOC/cds_model/cds_objects/hvideobroadcast_p.h \
    $$SRC_LOC/cds_model/cds_objects/hcontainer.h \
    $$SRC_LOC/cds_model/cds_objects/hcontainer_p.h \
    $$SRC_LOC/cds_model/cds_objects/hstoragefolder.h \
    $$SRC_LOC/cds_model/cds_objects/hstoragefolder_p.h \
    $$SRC_LOC/cds_model/cds_objects/hperson.h \
    $$SRC_LOC/cds_model/cds_objects/hperson_p.h \
    $$SRC_LOC/cds_model/cds_objects/hmusicartist.h \
    $$SRC_LOC/cds_model/cds_objects/hmusicartist_p.h \
    $$SRC_LOC/cds_model/cds_objects/hplaylistcontainer.h \
    $$SRC_LOC/cds_model/cds_objects/hplaylistcontainer_p.h \
    $$SRC_LOC/cds_model/cds_objects/halbum.h \
    $$SRC_LOC/cds_model/cds_objects/halbum_p.h \
    $$SRC_LOC/cds_model/cds_objects/hmusicalbum.h \
    $$SRC_LOC/cds_model/cds_objects/hmusicalbum_p.h \
    $$SRC_LOC/cds_model/cds_objects/hphotoalbum.h \
    $$SRC_LOC/cds_model/cds_objects/hphotoalbum_p.h \
    $$SRC_LOC/cds_model/cds_objects/hgenrecontainer.h \
    $$SRC_LOC/cds_model/cds_objects/hgenrecontainer_p.h \
    $$SRC_LOC/cds_model/cds_objects/hmoviegenre.h \
    $$SRC_LOC/cds_model/cds_objects/hmoviegenre_p.h \
    $$SRC_LOC/cds_model/cds_objects/hmusicgenre.h \
    $$SRC_LOC/cds_model/cds_objects/hmusicgenre_p.h \
    $$SRC_LOC/cds_model/cds_objects/hchannelgroup.h \
    $$SRC_LOC/cds_model/cds_objects/hchannelgroup_p.h \
    $$SRC_LOC/cds_model/cds_objects/haudiochannelgroup.h \
    $$SRC_LOC/cds_model/cds_objects/haudiochannelgroup_p.h \
    $$SRC_LOC/cds_model/cds_objects/hvideochannelgroup.h \
    $$SRC_LOC/cds_model/cds_objects/hvideochannelgroup_p.h \
    $$SRC_LOC/cds_model/cds_objects/hepgcontainer.h \
    $$SRC_LOC/cds_model/cds_objects/hepgcontainer_p.h \
    $$SRC_LOC/cds_model/cds_objects/hstoragesystem.h \
    $$SRC_LOC/cds_model/cds_objects/hstoragesystem_p.h \
    $$SRC_LOC/cds_model/cds_objects/hstoragevolume.h \
    $$SRC_LOC/cds_model/cds_objects/hstoragevolume_p.h \
    $$SRC_LOC/cds_model/cds_objects/hbookmarkfolder.h \
    $$SRC_LOC/cds_model/cds_objects/hbookmarkfolder_p.h

SOURCES += \
    $$SRC_LOC/cds_model/hgenre.cpp \
    $$SRC_LOC/cds_model/hdatetimerange.cpp \
    $$SRC_LOC/cds_model/hsortinfo.cpp \
    $$SRC_LOC/cds_model/hdeviceudn.cpp \
    $$SRC_LOC/cds_model/hprice.cpp \
    $$SRC_LOC/cds_model/hmatching_id.cpp \
    $$SRC_LOC/cds_model/hchannel_id.cpp \
    $$SRC_LOC/cds_model/hcdsclassinfo.cpp \
    $$SRC_LOC/cds_model/hpersonwithrole.cpp \
    $$SRC_LOC/cds_model/hcontentduration.cpp \
    $$SRC_LOC/cds_model/hchannelgroupname.cpp \
    $$SRC_LOC/cds_model/hforeignmetadata.cpp \
    $$SRC_LOC/cds_model/hprogramcode.cpp \
    $$SRC_LOC/cds_model/hstatevariablecollection.cpp \
    $$SRC_LOC/cds_model/hscheduledtime.cpp \
    $$SRC_LOC/cds_model/datasource/habstract_cds_datasource.cpp \
    $$SRC_LOC/cds_model/datasource/hcds_datasource.cpp \
    $$SRC_LOC/cds_model/datasource/hrootdir.cpp \
    $$SRC_LOC/cds_model/datasource/hfsys_datasource.cpp \
    $$SRC_LOC/cds_model/datasource/hcds_datasource_configuration.cpp \
    $$SRC_LOC/cds_model/datasource/hfsys_datasource_configuration.cpp \
    $$SRC_LOC/cds_model/model_mgmt/hcds_fsys_reader_p.cpp \
    $$SRC_LOC/cds_model/model_mgmt/hcdsobjectdata_p.cpp \
    $$SRC_LOC/cds_model/model_mgmt/hcdsproperty_db.cpp \
    $$SRC_LOC/cds_model/model_mgmt/hcdsproperties.cpp \
    $$SRC_LOC/cds_model/model_mgmt/hcdsproperty.cpp \
    $$SRC_LOC/cds_model/model_mgmt/hcdspropertyinfo.cpp \
    $$SRC_LOC/cds_model/model_mgmt/hcds_dlite_serializer.cpp \
    $$SRC_LOC/cds_model/cds_objects/hobject.cpp \
    $$SRC_LOC/cds_model/cds_objects/hitem.cpp \
    $$SRC_LOC/cds_model/cds_objects/haudioitem.cpp \
    $$SRC_LOC/cds_model/cds_objects/haudioprogram.cpp \
    $$SRC_LOC/cds_model/cds_objects/haudiobroadcast.cpp \
    $$SRC_LOC/cds_model/cds_objects/hbookmarkitem.cpp \
    $$SRC_LOC/cds_model/cds_objects/hepgitem.cpp \
    $$SRC_LOC/cds_model/cds_objects/haudiobook.cpp \
    $$SRC_LOC/cds_model/cds_objects/hmusictrack.cpp \
    $$SRC_LOC/cds_model/cds_objects/hmusicvideoclip.cpp \
    $$SRC_LOC/cds_model/cds_objects/himageitem.cpp \
    $$SRC_LOC/cds_model/cds_objects/hmovie.cpp \
    $$SRC_LOC/cds_model/cds_objects/hphoto.cpp \
    $$SRC_LOC/cds_model/cds_objects/htextitem.cpp \
    $$SRC_LOC/cds_model/cds_objects/hplaylistitem.cpp \
    $$SRC_LOC/cds_model/cds_objects/hvideoitem.cpp \
    $$SRC_LOC/cds_model/cds_objects/hvideoprogram.cpp \
    $$SRC_LOC/cds_model/cds_objects/hvideobroadcast.cpp \
    $$SRC_LOC/cds_model/cds_objects/hcontainer.cpp \
    $$SRC_LOC/cds_model/cds_objects/hstoragefolder.cpp \
    $$SRC_LOC/cds_model/cds_objects/hperson.cpp \
    $$SRC_LOC/cds_model/cds_objects/hmusicartist.cpp \
    $$SRC_LOC/cds_model/cds_objects/hplaylistcontainer.cpp \
    $$SRC_LOC/cds_model/cds_objects/halbum.cpp \
    $$SRC_LOC/cds_model/cds_objects/hmusicalbum.cpp \
    $$SRC_LOC/cds_model/cds_objects/hphotoalbum.cpp \
    $$SRC_LOC/cds_model/cds_objects/hgenrecontainer.cpp \
    $$SRC_LOC/cds_model/cds_objects/hmoviegenre.cpp \
    $$SRC_LOC/cds_model/cds_objects/hmusicgenre.cpp \
    $$SRC_LOC/cds_model/cds_objects/hchannelgroup.cpp \
    $$SRC_LOC/cds_model/cds_objects/haudiochannelgroup.cpp \
    $$SRC_LOC/cds_model/cds_objects/hvideochannelgroup.cpp \
    $$SRC_LOC/cds_model/cds_objects/hepgcontainer.cpp \
    $$SRC_LOC/cds_model/cds_objects/hstoragesystem.cpp \
    $$SRC_LOC/cds_model/cds_objects/hstoragevolume.cpp \
    $$SRC_LOC/cds_model/cds_objects/hbookmarkfolder.cpp
    