version: 3.23.3.{build}
image: Visual Studio 2026
configuration: Release
skip_commits:
  files:
    - '.github/*'
    - '.gitignore'
    - '*.md'

environment:
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2026
      QT6: C:\Qt\6.11.1\msvc2022_64
      VCVARS: C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat
      ARCHITECTURE: x86_64
      WARNINGS_AS_ERRORS: ON
      PYTHON: "C:\\Python314-x64"
      GIT_CLONE_PROTECTION_ACTIVE: false
      NOMACS_DEPENDENCIES: C:/projects/nomacs/3rd-party
      MS_CMAKE_PATH: C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin

    certpwd:
      secure: lqgUngzqY8panUxQ6C3IYQj4qZ8JYvMak5mH0ihm/ffnkTHADsqgPkXmI70gXVww

install:
    - appveyor DownloadFile "https://github.com/novomesk/downloads/raw/main/nasm-2.16.03-win64.zip" -FileName "nasm.zip"
    - appveyor DownloadFile "https://github.com/novomesk/downloads/raw/refs/heads/main/nomacs/nomacs-dependencies-2026-07-20.7z" -FileName "nomacs-dependencies.7z"
    - 7z x "nasm.zip"
    - mkdir C:\projects\nomacs\3rd-party
    - 7z x -oC:\projects\nomacs\3rd-party "nomacs-dependencies.7z"
    - move nasm-* NASM
    - set PATH=%MS_CMAKE_PATH%;%PYTHON%;%PYTHON%\\Scripts;%PATH%;%CD%\NASM;
    - nasm -v
    - call "%VCVARS%"

build_script:
    - mkdir build
    - cd build
    - cmake -G "NMake Makefiles" -DCMAKE_PREFIX_PATH=%QT6%;%NOMACS_DEPENDENCIES% -DCMAKE_INSTALL_PREFIX=%PWD%\installer\nomacs.x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DOpenCV_DIR=%NOMACS_DEPENDENCIES%/lib -DENABLE_QUAZIP=ON ../ImageLounge
    - nmake
    - nmake install
    - cd ..

after_build:
    - cd installer
    # make msi installer & sign nomacs
    - call make-msi-setup.bat %certpwd%
    #- call make-inno-setup.bat %certpwd%
    - call python ../scripts/make-portable.py

artifacts:
    - path: 'installer/nomacs-portable-win.zip'
      name: nomacs-portable

    - path: 'installer/nomacs-setup-x64.msi'
      name: nomacs-installer

#    - path: 'installer/nomacs-setup-x64.exe'
#      name: nomacs-multi-user-installer

    - path: 'installer/nomacs.x64/translations'
      name: translations
      type: zip
