FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update

RUN apt install -y bash coreutils git git-lfs curl wget gnupg ca-certificates tar gzip unzip sudo

RUN echo "deb http://archive.neon.kde.org/user jammy main" > \
 /etc/apt/sources.list.d/neon.list \
 && wget -qO - https://archive.neon.kde.org/public.key | apt-key add - \
 && apt-get update

RUN apt install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libqt6svg6-dev libqt6core5compat6-dev qt6-l10n-tools qt6-image-formats-plugins libexiv2-dev libraw-dev libopencv-dev libtiff-dev build-essential git cmake lcov libgtest-dev libgl-dev curl kf6-kimageformat-plugins libheif-dev ninja-build clang clang-format clang-tidy fuse3 file rsync

COPY ./scripts/build-linuxdeploy.sh ./
RUN ./build-linuxdeploy.sh

RUN apt upgrade -y

RUN apt clean && rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENTRYPOINT []
CMD []
USER root
