FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update

RUN apt install -y bash coreutils git curl wget gnupg ca-certificates tar gzip unzip sudo

RUN apt install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libqt6svg6-dev libqt6core5compat6-dev qt6-l10n-tools qt6-image-formats-plugins libexiv2-dev libraw-dev libopencv-dev libtiff-dev build-essential git cmake lcov libgtest-dev libgl-dev curl ninja-build libquazip1-qt6-dev clang clang-format clang-tidy fuse3

RUN apt clean && rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENTRYPOINT []
CMD []
USER root
