.TH imginfo 1 "20 June 2004" "Version 1.701.0" "JasPer Manual"

.SH NAME
imginfo \- Image information utility

.SH SYNOPSIS
.B imginfo
.RI [ options ]

.SH DESCRIPTION
The
.B imginfo
command displays information about an image.
Please use the \-\-help command
line switch and the JasPer Software Reference Manual for more information.

.SH SEE ALSO
.IR jasper (1)

.SH AUTHOR
Michael D. Adams <mdadams@ieee.org>
This manpage was initially written by Roland Stigge <stigge@antcom.de> for
the Debian Project.
