.TH jasper 1 "20 June 2004" "Version 1.701.0" "JasPer Manual"

.SH NAME
jasper \- File format converter specialized in JPEG-2000 encoding

.SH SYNOPSIS
.B jasper
.RI [ options ]

.SH DESCRIPTION
The
.B jasper
command converts to and from JPEG-2000 files. Please use the \-\-help command
line switch and the JasPer Software Reference Manual for more information.

.SH AUTHOR
Michael D. Adams <mdadams@ieee.org>
This manpage was initially written by Roland Stigge <stigge@antcom.de> for
the Debian Project.
