.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH nomacs 1 "July 13, 2012" "" "nomacs - ImageLounge"

.SH NAME
nomacs \- is a fast and small image viewer with the capability of 
synchronizing multiple instances

.SH SYNOPSIS
.B nomacs
.RI [ file ]
.br

.SH DESCRIPTION
 \fBnomacs\fP is an image viewer with capability of syncing multiple instances
 nomacs is a free image viewer for windows and linux systems, which is
 licensed under the GNU General Public License v3. nomacs is small, fast and 
 able to handle the most common image formats. Additionally it is possible to
 synchronize multiple viewers. A synchronization of viewers running on
 the same computer or via LAN is possible. It allows one to compare images
 and spot the differences (e.g. schemes of architects to show the
 progress).

.SH OPTIONS

you can supply an image file to nomacs and it will open it immediately. 

.SH AUTHORS
Markus Diem <markus@nomacs.org>

Stefan Fiel <stefan@nomacs.org>

Florian Kleber <florian@nomacs.org>
