.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH nomacs 1 "July 13, 2012" "" "nomacs - ImageLounge"

.SH NAME
nomacs \- is a free, open source image viewer, which supports multiple platforms. 

.SH SYNOPSIS
.B nomacs
.RI [ file ]
.br

.SH DESCRIPTION
\fBnomacs\fP nomacs is a free, open source image viewer, which supports multiple platforms. You can use it for viewing all common image formats including RAW and psd images.
nomacs includes image manipulation methods for adjusting brightness, contrast, saturation, hue, gamma, exposure. It has a pseudo color function which allows creating false color images. A unique feature of nomacs is the synchronization of multiple instances. With this feature you can easily compare images by zooming and/or panning at the exactly same position or even by overlaying them with different opacity.
nomacs is licensed under the GNU General Public License v3 and available for Windows, Linux, FreeBSD, and OS/2. It is free for private and commercial use.

.SH OPTIONS

you can supply an image file to nomacs and it will open it immediately. 

.SH AUTHORS
Markus Diem <markus@nomacs.org>

Stefan Fiel <stefan@nomacs.org>

Florian Kleber <florian@nomacs.org>
