#!/usr/bin/perl

# cpan XML::{Twig,Parser} to install the libraries

use XML::Twig;
use XML::Parser;

my $xml = XML::Twig->new(pretty_print => 'indented');

$xml->parse(\*STDIN);
$xml->print();

# That's all Folks!
##
